insert into book (id, title, authors) values (1, 'Pierwsza książka', 'Jan Kowalski');
insert into book (id, title, authors) values (2, 'Druga książka', 'Zbigniew Nowak');
insert into book (id, title, authors) values (3, 'Trzecia książka', 'Janusz Jankowski');
insert into book (id, title, authors) values (4, 'Korek', 'Theodor Söderholm');
insert into book (id, title, authors) values (5, 'Berzdej party', 'Peter Moller');
insert into book (id, title, authors) values (6, 'Ewrybady pomarancze', 'Allan Nordlund');
insert into book (id, title, authors) values (7, 'Jak zrazac do siebie ludzi', 'Liam Lagerlöf');
insert into book (id, title, authors) values (8, 'OK puta lets go', 'Tommy Hagström');
insert into book (id, title, authors) values (9, 'Katapulty i kotlety', 'Lars Untheläär');
insert into book (id, title, authors) values (10, 'Sermaci', 'Dunnere Collier');
insert into book (id, title, authors) values (11, 'Man With Silver', 'Linik Leja');
insert into book (id, title, authors) values (12, 'Owl Of The Undead', 'Prym Babinski');
insert into book (id, title, authors) values (13, 'Ogres Without Time', 'Longin Wojnowski');
insert into book (id, title, authors) values (14, 'Wizards Of Heaven', 'Karol Kuzio');
insert into book (id, title, authors) values (15, 'Gangsters And Armies', 'Apoloniusz Matula');
insert into book (id, title, authors) values (16, 'Monks And Lions', 'Rudolf Szolkowy');
insert into book (id, title, authors) values (17, 'Root Of The Shield', 'Felicjan Zdzanski');
insert into book (id, title, authors) values (18, 'Success Of Time', 'Piotr Piekut');
insert into book (id, title, authors) values (19, 'Sailing Into History', 'Strahinja Kolarov');
insert into book (id, title, authors) values (20, 'Breath Of The Swamp', 'Boguljub Novacek');
insert into book (id, title, authors) values (21, 'Hero Of Hell', 'Gvozden Sholokhov');
insert into book (id, title, authors) values (22, 'Lord Can Sing', 'Bora Slavik');
insert into book (id, title, authors) values (23, 'Butcher Of Humor', 'Bogomil Cherkassky');
insert into book (id, title, authors) values (24, 'Hunter Arrangement', 'Lado Kohut');
insert into book (id, title, authors) values (25, 'Serpent Strategy', 'Sobieslaw Chaykovskiy');
insert into book (id, title, authors) values (26, 'Mime And Buffoon', 'Mirek Svehla');
insert into book (id, title, authors) values (27, 'Soldier And Friend', 'Mislav Gospod');
insert into book (id, title, authors) values (28, 'Songs Abroad', 'Yavor Lhotzky');
insert into book (id, title, authors) values (29, 'Stunts Job', 'Giragos Sibrian');
insert into book (id, title, authors) values (30, 'Climax Of The Village', 'Vanoush Dzaghgouni');
insert into book (id, title, authors) values (31, 'Ambitious In My Idea', 'Dirayr Ojaghian');
insert into book (id, title, authors) values (32, 'Palace Of Summer', 'Vartivar Avetisyan');
insert into book (id, title, authors) values (33, 'Chamber Without Faith', 'Babeg Jambazian');
insert into book (id, title, authors) values (34, 'Forsaken By The City', 'Vazken Yerevanian');
insert into book (id, title, authors) values (35, 'Eliminating The Home Of DemonsClown Secret', 'Lazarus Altman');
insert into book (id, title, authors) values (36, 'Fool During My Travel', 'Izzy Zangwill');
insert into book (id, title, authors) values (37, 'Dog Project', 'Samson Gaster');
insert into book (id, title, authors) values (38, 'Raven Lives With Me', 'Ivrit Marks');
insert into book (id, title, authors) values (39, 'Wife And Agent', 'Joop Kostiner');
insert into book (id, title, authors) values (40, 'Agent And Lord', 'Dan Zeev');
insert into book (id, title, authors) values (41, 'Journeys Can Dance', 'Barrak Barnato');
insert into book (id, title, authors) values (42, 'Fire Of Parody', 'Karmel Stephany');
insert into book (id, title, authors) values (43, 'Suspicious Of My Island', 'Yaphet Sarlin');
insert into book (id, title, authors) values (44, 'Accomplishment Of Fantasy', 'Tamas Rothschild');
insert into book (id, title, authors) values (45, 'Angels Of The Broken Banner', 'Maël Delisle');
insert into book (id, title, authors) values (46, 'Werewolves And Vultures', 'Maël Delisle');
insert into book (id, title, authors) values (47, 'Starting Swords', 'Jean-Marie Gallois');
insert into book (id, title, authors) values (48, 'Companion Of The River', 'Baudouin Loupe');
insert into book (id, title, authors) values (49, 'Wives Of Desire', 'Nathan Corriveau');
insert into book (id, title, authors) values (50, 'Decay Without Faith', 'Marc MacGilleDhonaghart');
insert into book (id, title, authors) values (51, 'Weep For The Jungle', 'Martainn MacPhàdraig');
insert into book (id, title, authors) values (52, 'Ancients Of The Universe', 'Gòrdan MacIlleChiar');
insert into book (id, title, authors) values (53, 'Sins Of The Future', 'Farkas Salamon');
insert into book (id, title, authors) values (54, 'Imps And Freaks', 'Fekete Szebasztián');
insert into book (id, title, authors) values (55, 'Faith Of My Destiny', 'Somogyi Jusztusz');
insert into book (id, title, authors) values (56, 'Woman In My House', 'Király Megyer');
insert into book (id, title, authors) values (57, 'Cooks And Humans', 'Pásztor József');
insert into book (id, title, authors) values (58, 'Queens And Secret Admirers', 'Nathaniel Twitter');
insert into book (id, title, authors) values (59, 'Nations Of The Seas', 'Ernest Reed');
insert into book (id, title, authors) values (60, 'Ceremony In The City', 'August Lovell');
insert into book (id, title, authors) values (61, 'Numb In History', 'Gymnasium Maius');
insert into book (id, title, authors) values (62, 'Dearest Of My Admiration', 'Adamus Reburrus');
insert into book (id, title, authors) values (63, 'Pilot In The Beginning Of Time', 'Albanus Lucio');
insert into book (id, title, authors) values (64, 'Origin Of The Evening', 'Sphaerio Nectaridus');
insert into book (id, title, authors) values (65, 'Anxious For The Secrets Of The Ocean', 'Guilio Michaelides');
insert into book (id, title, authors) values (66, 'Rebirth Of The Galaxy', 'Theseus Perris');
insert into book (id, title, authors) values (67, 'Heroes And Aliens', 'Ganymede Pitera');
insert into book (id, title, authors) values (68, 'Intruders Of The Outlands', 'Cepheus Muto');
insert into book (id, title, authors) values (69, 'Honored By My Country', 'Clio Milas');
insert into book (id, title, authors) values (70, 'Talk To Secrets', 'Spyridon Antonopoulos');
